isa(cat, tom)
isa(cat, tim)
isa(cat, tam)
isa(cat, tup)
isa(cat, top)
-isa(cat, bat)
-isa(cat, rat)
-isa(cat, put)
isa(mouse, jerry)
isa(mouse, mousea)
isa(mouse, mouseb)
isa(mouse, mousec)
-isa(mouse, louse)
-isa(mouse, slouse)
-isa(mouse, tlouse)
-isa(mouse, ttlouse)
-isa(mouse, tttlouse)
-isa(mouse, ttttlouse)
isa(human, socrates)
isa(human, socratesa)
isa(human, socratesb)
isa(human, socratesc)
-isa(human, puman)
-isa(human, ppuman)
-isa(human, pppuman)
-isa(human, ppppuman)
-isa(human, pppppuman)
isa(robot, rob)
isa(robot, roba)
isa(robot, robb)
isa(robot, robc)
-isa(robot, puman)
-isa(robot, ppuman)
-isa(robot, pppuman)
-isa(robot, pppppuman)
isa(animal, an)
isa(rodent, ro)
-isa(rodent, nro)
isa(mortal, mo)
-isa(mortal, nmo)
-isa(animal, nan)

isa(mouse, rodent)
-isa(cat, rodent)
isa(animal, cat)
isa(animal, rodent)
-isa(animal, human)
isa(mortal, human)
isa(mortal, animal)
-isa(mortal, robot)

isa(X, Y) :- isa(X, Z), isa(Z, Y)
-isa(X, Y) :- -isa(X, Z), isa(Z, Y)

isa(mortal, socrates)!
-isa(mortal, rob)!
isa(mortal, tom)!
isa(mortal, jerry)!
isa(rodent, jerry)!
-isa(rodent, rob)!
-isa(rodent, socrates)!
-isa(rodent, tom)!
isa(rodent, jerry)!
-isa(human, tom)!
-isa(human, jerry)!
-isa(human, rob)!
isa(human, socrates)!
isa(animal, tom)!
isa(animal, jerry)!
-isa(animal, rob)!
-isa(animal, socrates)!
isa(cat, tom)!
-isa(cat, jerry)!
-isa(cat, socrates)!
-isa(cat, rob)!
isa(mouse, jerry)!
-isa(mouse, tom)!
-isa(mouse, socrates)!
-isa(mouse, rob)!
