larger(ten, nine)
larger(eleven, ten)
larger(twelve, eleven)
larger(thirteen, twelve)
larger(fourteen, thirteen)
larger(fifteen, fourteen)
larger(sixteen, fifteen)
larger(seventeen, sixteen)
larger(eighteen, seventeen)
larger(nineteen, eighteen)
larger(twenty, nineteen)

larger(twenty, ten)!
larger(twenty, nine)!
larger(twenty, six)!
larger(twenty, seven)!
larger(twenty, one)!
larger(twenty, two)!
larger(twenty, three)!
larger(eleven, ten)!
larger(eleven, nine)!
larger(eleven, six)!
larger(eleven, seven)!
larger(eleven, one)!
larger(eleven, two)!
larger(eleven, three)!
larger(twelve, ten)!
larger(twelve, nine)!
larger(twelve, six)!
larger(twelve, seven)!
larger(twelve, one)!
larger(twelve, two)!
larger(twelve, three)!
larger(thirteen, ten)!
larger(thirteen, nine)!
larger(thirteen, six)!
larger(thirteen, seven)!
larger(thirteen, one)!
larger(thirteen, two)!
larger(thirteen, three)!
